import { ProjectItem } from "@/types/project";

export const projectData: ProjectItem[] = [
  {
    id: 1,
    title: "Yatrasia",
    description: "yatrasia_desc",
    image: "/images/projects/yatrasia.jpg",
    frontend: ["NextJS", "React", "TypeScript", "HTML", "CSS", "Material UI"],
    backend: ["NodeJS", "Express", "Laravel"],
    website: "https://www.yatrasia.com/",
  },
  {
    id: 2,
    title: "Yatrasia",
    description: "yatrasia_desc2",
    image: "/images/projects/yatrasia.jpg",
    frontend: ["NextJS", "React", "TypeScript", "HTML", "CSS", "Material UI"],
    backend: ["NodeJS", "Express", "Laravel"],
    website: "https://www.yatrasia.com/",
  },
  {
    id: 3,
    title: "Yatrasia",
    description: "yatrasia_desc3",
    image: "/images/projects/yatrasia.jpg",
    frontend: ["NextJS", "React", "TypeScript", "HTML", "CSS", "Material UI"],
    backend: ["NodeJS", "Express", "Laravel"],
    website: "https://www.yatrasia.com/",
  },
  {
    id: 4,
    title: "Yatrasia",
    description: "yatrasia_desc3",
    image: "/images/projects/yatrasia.jpg",
    frontend: ["NextJS", "React", "TypeScript", "HTML", "CSS", "Material UI"],
    backend: ["NodeJS", "Express", "Laravel"],
    website: "https://www.yatrasia.com/",
  },
  {
    id: 5,
    title: "Yatrasia",
    description: "yatrasia_desc3",
    image: "/images/projects/yatrasia.jpg",
    frontend: ["NextJS", "React", "TypeScript", "HTML", "CSS", "Material UI"],
    backend: ["NodeJS", "Express", "Laravel"],
    website: "https://www.yatrasia.com/",
  },
  {
    id: 6,
    title: "Yatrasia",
    description: "yatrasia_desc3",
    image: "/images/projects/yatrasia.jpg",
    frontend: ["NextJS", "React", "TypeScript", "HTML", "CSS", "Material UI"],
    backend: ["NodeJS", "Express", "Laravel"],
    website: "https://www.yatrasia.com/",
    github: "https://www.yatrasia.com/",
  },
];
