import type { Metadata } from "next";
import About from "@/components/About";

export const metadata: Metadata = {
  title: "Home | Portfolio",
  description: "Generated by create next app",
};

const Home = () => {
  return (
    <>
      <About />
    </>
  );
};

export default Home;
