import type { Metadata } from "next";
import About from "@/components/About";
import Thanks from "@/components/Thank";
import Skills from "@/components/Skills";
import Information from "@/components/Info";
import Projects from "@/components/Projects";

export const metadata: Metadata = {
  title: "Home | Portfolio",
  description: "Generated by create next app",
};

const Home = () => {
  return (
    <>
      <About />
      <Information />
      <Skills />
      <Projects />
      <Thanks />
    </>
  );
};

export default Home;
